package papersappsdk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Items Items Response Schema
//
// # Set of items
//
// swagger:model Items
type Items struct {

	// Items list
	Items []*Item `json:"items"`

	Total int64 `json:"total,omitempty"`

	// Scroll id to be used to fetch the next batch of results
	ScrollID string `json:"scroll_id,omitempty"`
}
