// Code generated by go-swagger; DO NOT EDIT.

package papersappsdk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Empty Empty Schema
//
// swagger:model Empty
type Empty interface{}
