// Code generated by go-swagger; DO NOT EDIT.

package papersappsdk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Error Error Schema
//
// swagger:model Error
type Error struct {

	// Error code
	// Enum: [collection_not_found invalid_action not_found]
	Code string `json:"code,omitempty"`

	// Message that can be displayed to user
	Message string `json:"message,omitempty"`
}

// Validate validates this error
func (m *Error) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var errorTypeCodePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["collection_not_found","invalid_action","not_found"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		errorTypeCodePropEnum = append(errorTypeCodePropEnum, v)
	}
}

const (

	// ErrorCodeCollectionNotFound captures enum value "collection_not_found"
	ErrorCodeCollectionNotFound string = "collection_not_found"

	// ErrorCodeInvalidAction captures enum value "invalid_action"
	ErrorCodeInvalidAction string = "invalid_action"

	// ErrorCodeNotFound captures enum value "not_found"
	ErrorCodeNotFound string = "not_found"
)

// prop value enum
func (m *Error) validateCodeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, errorTypeCodePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Error) validateCode(formats strfmt.Registry) error {
	if swag.IsZero(m.Code) { // not required
		return nil
	}

	// value enum
	if err := m.validateCodeEnum("code", "body", m.Code); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this error based on context it is used
func (m *Error) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Error) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Error) UnmarshalBinary(b []byte) error {
	var res Error
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
