package papersappsdk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// File File Schema
//
// swagger:model File
type File struct {

	// File creation timestamp
	Created string `json:"created,omitempty"`

	// File format
	FileType string `json:"file_type,omitempty"`

	// File name
	Name string `json:"name,omitempty"`

	// Number of pages
	Pages float64 `json:"pages,omitempty"`

	// SHA256 hash of the file
	Sha256 string `json:"sha256,omitempty"`

	// File size in bytes
	Size float64 `json:"size,omitempty"`

	// File type
	// Enum: [article supplement]
	Type string `json:"type,omitempty"`

	// File download url
	URL string `json:"url,omitempty"`
}
