package papersappsdk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Item Item Response Schema
//
// swagger:model Item
type Item struct {

	// article
	Article *ArticleMetadata `json:"article,omitempty"`

	// custom metadata
	CustomMetadata interface{} `json:"custom_metadata,omitempty"`

	// custom type
	CustomType string `json:"custom_type,omitempty"`

	// ext ids
	ExtIds *ExtIds `json:"ext_ids,omitempty"`

	// files
	Files []File `json:"files,omitempty"`

	// Unique item id (e.g. 3cdfbfb9-07c2-4924-9eb3-3b790df74c0e)
	ID string `json:"id,omitempty"`

	// import data
	ImportData *ImportData `json:"import_data,omitempty"`

	// item type
	ItemType ItemType `json:"item_type,omitempty"`

	// SHA256 hash of the primary item PDF file
	PdfHash string `json:"pdf_hash,omitempty"`

	// user data
	UserData *UserData `json:"user_data,omitempty"`
}
