// Code generated by go-swagger; DO NOT EDIT.

package papersappsdk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ItemIds ItemIds Schema
//
// swagger:model ItemIds
type ItemIds struct {

	// Item ids (e.g. [3cdfbfb9-07c2-4924-9eb3-3b790df74c0e])
	ItemIds []string `json:"item_ids"`
}

// Validate validates this item ids
func (m *ItemIds) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this item ids based on context it is used
func (m *ItemIds) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ItemIds) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ItemIds) UnmarshalBinary(b []byte) error {
	var res ItemIds
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
