// Code generated by go-swagger; DO NOT EDIT.

package papersappsdk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UploadURL upload Url
//
// swagger:model UploadUrl
type UploadURL struct {

	// A pre-signed S3 PUT URL to upload the file to
	URL string `json:"url,omitempty"`
}

// Validate validates this upload Url
func (m *UploadURL) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this upload Url based on context it is used
func (m *UploadURL) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UploadURL) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UploadURL) UnmarshalBinary(b []byte) error {
	var res UploadURL
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
