package papersappsdk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Collections Collections Schema
//
// # Set of collections
//
// swagger:model Collections
type Collections struct {

	// collections
	Collections []*Collection `json:"collections"`
}
