package papersappsdk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ItemType ItemType schema
//
// swagger:model ItemType
type ItemType string

const (

	// ItemTypeAbstract captures enum value "abstract"
	ItemTypeAbstract ItemType = "abstract"

	// ItemTypeArticle captures enum value "article"
	ItemTypeArticle ItemType = "article"

	// ItemTypeArtwork captures enum value "artwork"
	ItemTypeArtwork ItemType = "artwork"

	// ItemTypeAudioRecording captures enum value "audio_recording"
	ItemTypeAudioRecording ItemType = "audio_recording"

	// ItemTypeBill captures enum value "bill"
	ItemTypeBill ItemType = "bill"

	// ItemTypeBlogPost captures enum value "blog_post"
	ItemTypeBlogPost ItemType = "blog_post"

	// ItemTypeBook captures enum value "book"
	ItemTypeBook ItemType = "book"

	// ItemTypeBookSection captures enum value "book_section"
	ItemTypeBookSection ItemType = "book_section"

	// ItemTypeCase captures enum value "case"
	ItemTypeCase ItemType = "case"

	// ItemTypeClinicalTrial captures enum value "clinical_trial"
	ItemTypeClinicalTrial ItemType = "clinical_trial"

	// ItemTypeComputerProgram captures enum value "computer_program"
	ItemTypeComputerProgram ItemType = "computer_program"

	// ItemTypeConferencePaper captures enum value "conference_paper"
	ItemTypeConferencePaper ItemType = "conference_paper"

	// ItemTypeDictionaryEntry captures enum value "dictionary_entry"
	ItemTypeDictionaryEntry ItemType = "dictionary_entry"

	// ItemTypeDocument captures enum value "document"
	ItemTypeDocument ItemType = "document"

	// ItemTypeEmail captures enum value "email"
	ItemTypeEmail ItemType = "email"

	// ItemTypeEncyclopediaArticle captures enum value "encyclopedia_article"
	ItemTypeEncyclopediaArticle ItemType = "encyclopedia_article"

	// ItemTypeFilm captures enum value "film"
	ItemTypeFilm ItemType = "film"

	// ItemTypeForumPost captures enum value "forum_post"
	ItemTypeForumPost ItemType = "forum_post"

	// ItemTypeGuidanceDocuments captures enum value "guidance_documents"
	ItemTypeGuidanceDocuments ItemType = "guidance_documents"

	// ItemTypeHearing captures enum value "hearing"
	ItemTypeHearing ItemType = "hearing"

	// ItemTypeInstantMessage captures enum value "instant_message"
	ItemTypeInstantMessage ItemType = "instant_message"

	// ItemTypeInterview captures enum value "interview"
	ItemTypeInterview ItemType = "interview"

	// ItemTypeLetter captures enum value "letter"
	ItemTypeLetter ItemType = "letter"

	// ItemTypeMagazine captures enum value "magazine"
	ItemTypeMagazine ItemType = "magazine"

	// ItemTypeManuscript captures enum value "manuscript"
	ItemTypeManuscript ItemType = "manuscript"

	// ItemTypeMap captures enum value "map"
	ItemTypeMap ItemType = "map"

	// ItemTypeNewspaperArticle captures enum value "newspaper_article"
	ItemTypeNewspaperArticle ItemType = "newspaper_article"

	// ItemTypePatent captures enum value "patent"
	ItemTypePatent ItemType = "patent"

	// ItemTypePodcast captures enum value "podcast"
	ItemTypePodcast ItemType = "podcast"

	// ItemTypePosterPresentation captures enum value "poster_presentation"
	ItemTypePosterPresentation ItemType = "poster_presentation"

	// ItemTypePresentation captures enum value "presentation"
	ItemTypePresentation ItemType = "presentation"

	// ItemTypeRadioBroadcast captures enum value "radio_broadcast"
	ItemTypeRadioBroadcast ItemType = "radio_broadcast"

	// ItemTypeReport captures enum value "report"
	ItemTypeReport ItemType = "report"

	// ItemTypeStatute captures enum value "statute"
	ItemTypeStatute ItemType = "statute"

	// ItemTypeThesis captures enum value "thesis"
	ItemTypeThesis ItemType = "thesis"

	// ItemTypeTvBroadcast captures enum value "tv_broadcast"
	ItemTypeTvBroadcast ItemType = "tv_broadcast"

	// ItemTypeVideoRecording captures enum value "video_recording"
	ItemTypeVideoRecording ItemType = "video_recording"

	// ItemTypeWebpage captures enum value "webpage"
	ItemTypeWebpage ItemType = "webpage"
)
