package papersappsdk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Token token
//
// swagger:model Token
type Token struct {

	// token
	Token string `json:"token,omitempty"`
}
