name: lint-govulncheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Go cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-cache

      - name: Lint ./operations
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./operations

      - name: Lint ./webapitestutil
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./webapitestutil

      - name: Lint ./openapi
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./openapi

      - name: Lint ./oapi-tool
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./oapi-tool

      - name: Vulnerabilities
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          for dir in ./operations ./webapitestutil ./openapi ./oapi-tool; do \
              cd $dir; govulncheck ./...; cd .. ; \
          done
